version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: "Setup Snyk"
          command: |
            sudo npm install -g snyk
      - checkout
      - run:
          name: "Install deps"
          command: |
            npm install
      - run:
          name: "Run Lint"
          command: |
            npm run lint
      - run:
          name: "Run Tests"
          command: |
            npm test
      - run:
          name: "Snyk Test"
          command: |
            snyk test --org=customer-facing-tools
      - run:
          name: "Monitor"
          command: |
            snyk monitor --org=customer-facing-tools
